### ISSUE TITLE
Transformation of multiline text removed line returns

### ISSUE THREAD

**Issue by mvanputt** [otnansirk/vscode-casing-convention#3]
This plugin does exactly what I needed for my workflow. However, it only enables text transformation of single lines. When I select multiple lines of text and want to apply a standard capitalization all of the line returns get removed and the selected text becomes a single line post transformation.

**Comment by otnansirk** [comment]
For multiple lines you can use like this. Is this what you want ?

https://github.com/otnansirk/vscode-casing-convention/assets/30102523/f5884b14-301d-460e-b335-3f0de2bc6fe9

**Comment by otnansirk** [comment]
Have solved in version [v1.1.2](https://github.com/otnansirk/vscode-casing-convention/releases/tag/v1.1.2) Please update to this version

**Comment by otnansirk** [comment]
Now you can select all.
